//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieuModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fml_ExpenseInfo
    {
        public int F_expI_ID { get; set; }
        public string F_expI_Note { get; set; }
        public int Ec_ID { get; set; }
        public int F_exp_ID { get; set; }
    
        public virtual ExpenseCategories ExpenseCategories { get; set; }
        public virtual Fml_Expenses Fml_Expenses { get; set; }
    }
}
