//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieuModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Img_ID { get; set; }
        public string Img_Name { get; set; }
        public string Img_Url { get; set; }
        public Nullable<int> Img_Relation_ID { get; set; }
        public string Img_Type { get; set; }
    }
}
