//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieuModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psn_Expenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Psn_Expenses()
        {
            this.Psn_ExpenseInfo = new HashSet<Psn_ExpenseInfo>();
        }
    
        public int P_exp_ID { get; set; }
        public string P_exp_Name { get; set; }
        public Nullable<System.DateTime> P_exp_Date { get; set; }
        public decimal P_exp_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Psn_ExpenseInfo> Psn_ExpenseInfo { get; set; }
    }
}
