//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieuModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueInfo
    {
        public int RevI_ID { get; set; }
        public string RevI_Note { get; set; }
        public int Rev_ID { get; set; }
        public int RevCateg_ID { get; set; }
    
        public virtual RevenueCategories RevenueCategories { get; set; }
        public virtual Revenues Revenues { get; set; }
    }
}
