//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieuModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int Vid_ID { get; set; }
        public string Vid_Name { get; set; }
        public string Vid_Url { get; set; }
        public Nullable<int> Vid_Relation_ID { get; set; }
        public string Vid_Type { get; set; }
    }
}
