//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyChiTieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fml_Expenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fml_Expenses()
        {
            this.Fml_ExpenseInfo = new HashSet<Fml_ExpenseInfo>();
        }
    
        public int F_exp_ID { get; set; }
        public string F_exp_Name { get; set; }
        public Nullable<System.DateTime> F_exp_Date { get; set; }
        public decimal F_exp_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fml_ExpenseInfo> Fml_ExpenseInfo { get; set; }
    }
}
